config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#welcome'

  resources :categories, only: [:new, :create]
  resources :posts, only: [:index, :show, :new, :create, :edit, :update] do
    resources :comments, only: [:create]
    get 'search', on: :collection
  end
  resources :comments, only: [:destroy]
  resources :profiles, only: [:index, :show]
  resources :products, only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment_text, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category

  has_one_attached :image
  has_many :comments, dependent: nil

  validates :title, :country, :state, :city, :text, presence: true
  validates :title, uniqueness: true
  validates :country, length: { is: 3 }
  validates :state, length: { is: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  enum :role, { regular: 10, admin: 20 }, default: :regular
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: nil
  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def check_admin
    redirect_to root_url, alert: t('.authorization_failure') if current_user.admin? == false
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    if @comment.save
      redirect_to post_path(@post.id), notice: t('.success')
    else
      redirect_to post_path(@post.id), alert: t('.failure')
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @comment.destroy
    flash[:notice] = t('.destroy_success')
    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :comment_text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    @posts = Post.last(3)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_admin, only: %i[new create edit update]
  before_action :set_post, only: %i[show edit update]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  def search
    @search = params['query']
    @posts = Post.where('country LIKE ?', "%#{@search.upcase}%")
    @posts = Post.where('title LIKE ?', "%#{@search.capitalize}%") unless @posts.any?
    @posts = Post.where('state LIKE ?', "%#{@search.upcase}%") unless @posts.any?
    @posts = Post.where('city LIKE ?', "%#{@search}%") unless @posts.any?
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = t('.success')
      redirect_to @post
    else
      flash.now[:alert] = t('.failure')
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = t('.update_success')
      redirect_to @post
    else
      flash.now[:alert] = t('.update_failure')
      render 'edit'
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :country, :state, :city,
                                 :category_id, :text, :image, :restaurant_tip,
                                 :tour_tip)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    response = Faraday.get('https://fakestoreapi.com/products')
    @products = JSON.parse(response.body)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/categories/_form.html.erb
<div class="form">
  <%= form_with(model: @category) do |f| %>
    <div class="mb-3">
      <%= f.label :name, class: "form-label fw-semibold" %>
      <%= f.text_field :name, class: "form-control" %>
      <% if(@category.errors.include? :name) %>
        <div class=" my-3 alert alert-danger">
          <ul>
            <% @category.errors.full_messages_for(:name).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="d-grid mb-3">
      <%= f.submit class: "button" %>
    </div>
  <% end %>
</div>

app/views/categories/_list.html.erb
<% if @categories.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= Service.human_attribute_name(:code) %></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-secondary text-center">
    <%= t '.message' %>
  </div>
<% end %>

app/views/categories/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>
<div>
  <%= render 'list' %>
</div>

app/views/home/welcome.html.erb
<div class="capa">
  <img src="/assets/capa.jpg" class="img-fluid vw-100" alt="Capa - Paisagem">
</div>
<div class="border">
  <h4>Últimas postagens</h4>
  <div class="container text-center">
    <div class="row align-items-center">
      <% @posts.each do |post| %>
        <div class="col">
          <div class="card">
            <% if post.image.attached? %>
              <%= image_tag post.image, class:"card-img-small"%>
            <% end %>
          </div>
          <%= link_to post.title, post, class: "link" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="itens">
    <a href="https://www.instagram.com/anitaluri/" class="link">
      <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
      </svg>
    </a>
  </div>
  <div class="itens">
    <a href="https://github.com/AnitaLuri" class="link">
      <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
      </svg>
    </a>
  </div>
  <div class="itens">
    <a href="https://www.linkedin.com/in/anita-luri-h-62543367/" class="link">
      <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
        <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
      </svg>
    </a>
  </div>
</div>
<div class="footer">
  <p> anitaluri.h@gmail.com </p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Diário de Viagem', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Viagens', posts_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Loja', products_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sobre', profiles_path , class: 'nav-link' %>
        </li>
      </ul>

      <% if user_signed_in? %>
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.name %>
              </a>
              <ul class="dropdown-menu dropdown-menu-lg-end">
                <%= button_to 'Sair', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </ul>
            </li>
          </ul>
        </div>
      <% else %>
        <%= link_to 'Login',  new_user_session_path, class: "btn btn-outline-dark" %>
      <%end%>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diario De Viagem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
        <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;1,300;1,400&family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet">
  </head>

  <body class="body">
    <header>
      <%= render 'layouts/navbar' %>
    </header>
     <div class="container">
        <div class="my-3" >
          <% flash.each do |type, msg| %>
            <% if type == 'alert' %>
              <div class='alert alert-danger' >
                <%= msg %>
              </div>
            <% else %>
              <div class='alert alert-success' >
                <%= msg %>
              </div>
            <% end %>
          <% end %>
        </div>
        <%= yield %>
        <hr />
      </div>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
  </body>
</html>

app/views/posts/_comment.html.erb
<div class="container text-start">
  <% if user_signed_in? %>
    <div id="comment-form">
      <%= form_with(model: [@post, @comment]) do |f| %>
        <div class="mb-3">
          <%= f.label :comment_text, class: "form-label fw-semibold" %>
          <%= f.text_area :comment_text, class: "form-control" %>
          <% if(@comment.errors.include? :comment_text) %>
            <div class=" my-3 alert alert-danger">
              <ul>
                <% @comment.errors.full_messages_for(:comment_text).each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
        <div class="d-grid mb-3">
          <%= f.submit 'Incluir comentário', class: "button" %>
        </div>
      <% end %>
    </div>
  <% else %>
    <h4 class="title">Faça login para compartilhar sua experiência!</h4>
  <% end %>

<% if @comments.any? %>
  <h4 class="title">Outros comentários!</h4>
  <% @comments.each do |c| %>
    <div class='comment-box'>
      <div id="title-comment">
        <h4 class="title"><%= c.user.name %> </h4> <p>-  <%= c.created_at.strftime("%d/%m/%Y-%H:%M") %></p>
      </div>
      <br />
      <p><%= c.comment_text %></p>
      <% if current_user == c.user || current_user.try(:admin?) %>
        <div class="text-end">
          <%= button_to('Excluir', comment_path(c.id), method: :delete, class:"btn btn-outline-dark") %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<div class="form">
  <%= form_with(model: @post) do |f| %>
    <div class="mb-3">
      <%= f.label :title, class: "form-label fw-semibold" %>
      <%= f.text_field :title, class: "form-control" %>
      <% if(@post.errors.include? :title) %>
        <div class=" my-3 alert alert-danger">
          <ul>
            <% @post.errors.full_messages_for(:title).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.label :country, class: "form-label fw-semibold" %>
      <%= f.text_field :country, class: "form-control" %>
      <% if(@post.errors.include? :country) %>
        <div class=" my-3 alert alert-danger">
          <ul>
            <% @post.errors.full_messages_for(:country).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.label :state, class: "form-label fw-semibold" %>
      <%= f.text_field :state, class: "form-control" %>
      <% if(@post.errors.include? :state) %>
        <div class=" my-3 alert alert-danger">
          <ul>
            <% @post.errors.full_messages_for(:state).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.label :city, class: "form-label fw-semibold" %>
      <%= f.text_field :city, class: "form-control" %>
      <% if(@post.errors.include? :city) %>
        <div class=" my-3 alert alert-danger">
          <ul>
            <% @post.errors.full_messages_for(:city).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.label :category_id, class: "form-label fw-semibold" %>
      <%= f.collection_select :category_id, Category.all, :id, :name, class: "form-control" %>
      <%= link_to 'Criar nova Categoria', new_category_path, class: "button" %>
      <% if(@post.errors.include? :category_id) %>
        <div class=" my-3 alert alert-danger">
          <ul>
            <% @post.errors.full_messages_for(:category_id).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.label :text, class: "form-label fw-semibold" %>
      <%= f.text_area :text, class: "form-control" %>
      <% if(@post.errors.include? :text) %>
        <div class=" my-3 alert alert-danger">
          <ul>
            <% @post.errors.full_messages_for(:text).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div>
      <% if @post.image.attached? %>      
        <p style="font-size: 12px">Imagem cadastrada:</p>
        <%= image_tag @post.image, style: "width: 80px; display: block" %>
      <% end %>
    </div><br>
    <div class="mb-3">
      <%= f.label :image, class: "form-label fw-semibold" %>
      <%= f.file_field :image, accept: 'image/png, image/jpeg, image/svg', class: "form-control" %>
      <% if(@post.errors.include? :image) %>
        <div class=" my-3 alert alert-danger">
          <ul>
            <% @post.errors.full_messages_for(:image).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.label :restaurant_tip, class: "form-label fw-semibold" %>
      <%= f.text_area :restaurant_tip, class: "form-control" %>
      <% if(@post.errors.include? :restaurant_tip) %>
        <div class=" my-3 alert alert-danger">
          <ul>
            <% @post.errors.full_messages_for(:restaurant_tip).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.label :tour_tip, class: "form-label fw-semibold" %>
      <%= f.text_area :tour_tip, class: "form-control" %>
      <% if(@post.errors.include? :tour_tip) %>
        <div class=" my-3 alert alert-danger">
          <ul>
            <% @post.errors.full_messages_for(:tour_tip).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="d-grid mb-3">
      <%= f.submit class: "button" %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="border">
  <h2>Editar Postagem <%= @post.title  %></h2>
  <div id="back" class="text-end"> 
    <%= link_to 'Voltar', post_path(@post) , type:"button", class:"btn btn-outline-dark" %>
  </div>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div>
  <h3 class="title">Escolha um Destino!</h3>
</div>

<div class="form">
  <%= form_with(url: search_posts_path, method: :get) do |f| %>
    <div>
      <%= f.label :query, 'Buscar por Destino' %>
      <%= f.text_field :query, class:"form-input"%>
      <%= f.submit 'Buscar', class:"button" %>
    </div>
  <% end %>
</div>

<div class="form">
  <% if current_user.try(:admin?) %>
    <%= link_to 'Adicionar Postagem', new_post_path, class: "button " %>
  <% end %>
</div>

<div class="border">
  <div class="container text-center">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-sm-3 align-items-center">
      <% @posts.each do |post| %>
        <div class="col">
          <div class="card shadow-sm">
            <% if post.image.attached? %>
              <%= image_tag post.image, class:"card-img-small"%>
            <% end %>
            <div class="card-body">
              <h4><%= link_to post.title, post, class: "link" %></h4>
              <p class="card-text"><%= post.state %> - <%= post.city %></p>
              <small class="text-muted"><%= post.category.name%></small>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="border">
  <h2>Adicionar nova Postagem</h2>
  <%= render 'form' %>
</div>

app/views/posts/search.html.erb
<div class="form">
  <%= form_with(url: search_posts_path, method: :get) do |f| %>
    <div>
      <%= f.label :query, 'Buscar por Destino' %>
      <%= f.text_field :query,  class:"form-input"%>
      <%= f.submit 'Buscar', class:"button" %>
    </div>
  <% end %>
</div>

<div class="border">
  <% if @posts.any? %>
    <h2>Resultado da busca: <%= @search %> </h2>
    <div class="border">
  <div class="container text-center">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-sm-3 align-items-center">
      <% @posts.each do |post| %>
        <div class="col">
          <div class="card shadow-sm">
            <% if post.image.attached? %>
              <%= image_tag post.image, class:"card-img-small"%>
            <% end %>
            <div class="card-body">
              <h4><%= link_to post.title, post, class: "link" %></h4>
              <p class="card-text"><%= post.state %> - <%= post.city %></p>
              <small class="text-muted"><%= post.category.name%></small>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
  <% else %>
    <h2>Nenhum resultado encontrado para: <%= @search %> </h2>
    <%= link_to 'Voltar', posts_path, class:"button" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="border">
  <div class="container text-start">
    <div class="row align-items-center">
      <div class="col">
        <% if @post.image.attached? %>
          <%= image_tag @post.image, class:"card-img", width: '590px', height: '480px'%>
        <% end %>
      </div>
      <div class="col">
        <div>
          <h3><%= @post.title %></h3>
          <h4><%= @post.state%> - <%= @post.city %></h4>
          <small class="text-muted"><%= @post.category.name%></small>
        </div>
        <div>
          <p><%= @post.text %></p>
          <p><strong>Dica de Restaurante: </strong><%= @post.restaurant_tip %></p>
          <p><strong>Dica de Passeio: </strong><%= @post.tour_tip %></p>
        </div>
      </div>
    </div>
    <div class="form text-end">
      <% if current_user.try(:admin?) %>
        <%= link_to 'Editar', edit_post_path(@post.id), class: "btn btn-outline-dark" %>
      <% end %>
    </div>
  </div>
</div>
<div class="border">
  <%= render 'posts/comment' %>
</div>

app/views/products/index.html.erb
<div class="text-center">
  <h3 class="title">Alguns de itens úteis para sua próxima viagem!</h3>
</div>

<% if @products.empty? %>
  <p>Nenhum produto disponível no momento</p>
<% end %>

<div class="border">
  <div class="container text-center">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-sm-3 row-cols-sm-4 align-items-center">
      <% @products.each do |product| %>
        <div class="col">
          <div class="card shadow-sm">
            <%= image_tag product['image'], class:"card-img-small", style:"height:200px"%>
            <div class="card-body">
              <h4 class="link"><%= product['title'].split.first %></h4>
              <p class="card-text"><%= number_to_currency(product['price']) %></p>
              <small class="text-muted"><%= product['category']%></small>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div>
  <h2 class="title">Sobre quem desenvolveu</h2>
</div>

<div class="container border text-start">
  <div class="card-body">
    <div class="row align-items-center">
      <div class="col-md-9">
        <h3 class="title">Oi, meu nome é <strong>Anita</strong>! </h3>
        <p>Tenho 26 anos, me formei em Ciências Contábeis, estive nessa área por 7 anos e hoje 
        estou em transição de carreira. Me encontrei como desenvolvedora e estou buscando oportunidades 
        para adquirir mais conhecimento e experiências.</p>

        <p>Criei esse projeto para juntar alguns conhecimentos que adquiri até agora, exercitar boas 
        práticas de código e testes.</p>

        <p>Nesse projeto coloquei como objetivos principais: </p>
        <ul>
          <li> utilizar <strong>Docker</strong>;</li>
          <li> desenvolver em <strong>Ruby on Rails com TDD</strong>;</li>
          <li> ter <strong>alta cobertura</strong> de testes;</li>
          <li> utilizar o <strong>PostgreSQL</strong>;</li>
          <li> aplicar <strong>Bootstrap</strong>;</li>
          <li> consumir uma <strong>API</strong>.</li>
        </ul>
      </div>
      <div class="col-md-3 mb-4">
        <img src="/assets/eu.jpg" class="card-img" alt="Capa - Paisagem">
      </div>
    </div>
  </div>
</div>

<div class="container border">
  <h4>Outros Projetos: </h4>
  <div class="container text-center">
    <div class="row align-items-center">
      <div class="col">
        <a href="https://github.com/TreinaDev/insurance-app" class="link">
          <div class="card-small">
            <img src="/assets/insurance.png" class="card-img-small" alt="TreinaDev - Insurance" width="100%" height="120">
            TreinaDev
          </div>
        </a>
      </div>
      <div class="col">
        <a href="https://github.com/AnitaLuri/sistema-de-frete" class="link">
          <div class="card-small">
            <img src="/assets/frete.png" class="card-img-small" alt="TreinaDev - Sistema de Frete" width="100%" height="120">
            Sistema de Frete
          </div>
        </a>
      </div>
      <div class="col">
        <a href="https://github.com/AnitaLuri/convert" class="link">
          <div class="card-small">
            <img src="/assets/convert.png" class="card-img-small" alt="Alura - Conversor" width="100%" height="120">
            Conversor
          </div>
        </a>
      </div>
      <div class="col">
        <a href="https://github.com/AnitaLuri/ranking-alura" class="link">
          <div class="card-small">
            <img src="/assets/ranking.png" class="card-img-small" alt="Alura - Ranking" width="100%" height="120">
            Ranking
          </div>
        </a>
      </div>
    </div>
  </div>
</div>